//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.28 at 09:42:53 PM IST 
//


package com.test.amazon.core.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.test.amazon.core.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.test.amazon.core.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemSearchResponse }
     * 
     */
    public ItemSearchResponse createItemSearchResponse() {
        return new ItemSearchResponse();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items }
     * 
     */
    public ItemSearchResponse.Items createItemSearchResponseItems() {
        return new ItemSearchResponse.Items();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item }
     * 
     */
    public ItemSearchResponse.Items.Item createItemSearchResponseItemsItem() {
        return new ItemSearchResponse.Items.Item();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.EditorialReviews }
     * 
     */
    public ItemSearchResponse.Items.Item.EditorialReviews createItemSearchResponseItemsItemEditorialReviews() {
        return new ItemSearchResponse.Items.Item.EditorialReviews();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.OfferSummary }
     * 
     */
    public ItemSearchResponse.Items.Item.OfferSummary createItemSearchResponseItemsItemOfferSummary() {
        return new ItemSearchResponse.Items.Item.OfferSummary();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes createItemSearchResponseItemsItemItemAttributes() {
        return new ItemSearchResponse.Items.Item.ItemAttributes();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions createItemSearchResponseItemsItemItemAttributesPackageDimensions() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.Languages }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.Languages createItemSearchResponseItemsItemItemAttributesLanguages() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.Languages();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions createItemSearchResponseItemsItemItemAttributesItemDimensions() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets createItemSearchResponseItemsItemImageSets() {
        return new ItemSearchResponse.Items.Item.ImageSets();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet createItemSearchResponseItemsItemImageSetsImageSet() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.LargeImage }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.LargeImage createItemSearchResponseItemsItemImageSetsImageSetLargeImage() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.LargeImage();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.MediumImage }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.MediumImage createItemSearchResponseItemsItemImageSetsImageSetMediumImage() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.MediumImage();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.TinyImage }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.TinyImage createItemSearchResponseItemsItemImageSetsImageSetTinyImage() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.TinyImage();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.ThumbnailImage }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.ThumbnailImage createItemSearchResponseItemsItemImageSetsImageSetThumbnailImage() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.ThumbnailImage();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.SmallImage }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.SmallImage createItemSearchResponseItemsItemImageSetsImageSetSmallImage() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.SmallImage();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.SwatchImage }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.SwatchImage createItemSearchResponseItemsItemImageSetsImageSetSwatchImage() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.SwatchImage();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.LargeImage }
     * 
     */
    public ItemSearchResponse.Items.Item.LargeImage createItemSearchResponseItemsItemLargeImage() {
        return new ItemSearchResponse.Items.Item.LargeImage();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.MediumImage }
     * 
     */
    public ItemSearchResponse.Items.Item.MediumImage createItemSearchResponseItemsItemMediumImage() {
        return new ItemSearchResponse.Items.Item.MediumImage();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.SmallImage }
     * 
     */
    public ItemSearchResponse.Items.Item.SmallImage createItemSearchResponseItemsItemSmallImage() {
        return new ItemSearchResponse.Items.Item.SmallImage();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemLinks }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemLinks createItemSearchResponseItemsItemItemLinks() {
        return new ItemSearchResponse.Items.Item.ItemLinks();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Request }
     * 
     */
    public ItemSearchResponse.Items.Request createItemSearchResponseItemsRequest() {
        return new ItemSearchResponse.Items.Request();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.OperationRequest }
     * 
     */
    public ItemSearchResponse.OperationRequest createItemSearchResponseOperationRequest() {
        return new ItemSearchResponse.OperationRequest();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.OperationRequest.Arguments }
     * 
     */
    public ItemSearchResponse.OperationRequest.Arguments createItemSearchResponseOperationRequestArguments() {
        return new ItemSearchResponse.OperationRequest.Arguments();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.OperationRequest.HTTPHeaders }
     * 
     */
    public ItemSearchResponse.OperationRequest.HTTPHeaders createItemSearchResponseOperationRequestHTTPHeaders() {
        return new ItemSearchResponse.OperationRequest.HTTPHeaders();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.EditorialReviews.EditorialReview }
     * 
     */
    public ItemSearchResponse.Items.Item.EditorialReviews.EditorialReview createItemSearchResponseItemsItemEditorialReviewsEditorialReview() {
        return new ItemSearchResponse.Items.Item.EditorialReviews.EditorialReview();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.OfferSummary.LowestNewPrice }
     * 
     */
    public ItemSearchResponse.Items.Item.OfferSummary.LowestNewPrice createItemSearchResponseItemsItemOfferSummaryLowestNewPrice() {
        return new ItemSearchResponse.Items.Item.OfferSummary.LowestNewPrice();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.OfferSummary.LowestUsedPrice }
     * 
     */
    public ItemSearchResponse.Items.Item.OfferSummary.LowestUsedPrice createItemSearchResponseItemsItemOfferSummaryLowestUsedPrice() {
        return new ItemSearchResponse.Items.Item.OfferSummary.LowestUsedPrice();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.OfferSummary.LowestCollectiblePrice }
     * 
     */
    public ItemSearchResponse.Items.Item.OfferSummary.LowestCollectiblePrice createItemSearchResponseItemsItemOfferSummaryLowestCollectiblePrice() {
        return new ItemSearchResponse.Items.Item.OfferSummary.LowestCollectiblePrice();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.EANList }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.EANList createItemSearchResponseItemsItemItemAttributesEANList() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.EANList();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.ListPrice }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.ListPrice createItemSearchResponseItemsItemItemAttributesListPrice() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.ListPrice();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.TradeInValue }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.TradeInValue createItemSearchResponseItemsItemItemAttributesTradeInValue() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.TradeInValue();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.CatalogNumberList }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.CatalogNumberList createItemSearchResponseItemsItemItemAttributesCatalogNumberList() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.CatalogNumberList();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Height createItemSearchResponseItemsItemItemAttributesPackageDimensionsHeight() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Length }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Length createItemSearchResponseItemsItemItemAttributesPackageDimensionsLength() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Length();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Weight }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Weight createItemSearchResponseItemsItemItemAttributesPackageDimensionsWeight() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Weight();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Width createItemSearchResponseItemsItemItemAttributesPackageDimensionsWidth() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.PackageDimensions.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.Languages.Language }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.Languages.Language createItemSearchResponseItemsItemItemAttributesLanguagesLanguage() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.Languages.Language();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Height createItemSearchResponseItemsItemItemAttributesItemDimensionsHeight() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Length }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Length createItemSearchResponseItemsItemItemAttributesItemDimensionsLength() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Length();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Weight }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Weight createItemSearchResponseItemsItemItemAttributesItemDimensionsWeight() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Weight();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Width createItemSearchResponseItemsItemItemAttributesItemDimensionsWidth() {
        return new ItemSearchResponse.Items.Item.ItemAttributes.ItemDimensions.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.LargeImage.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.LargeImage.Height createItemSearchResponseItemsItemImageSetsImageSetLargeImageHeight() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.LargeImage.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.LargeImage.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.LargeImage.Width createItemSearchResponseItemsItemImageSetsImageSetLargeImageWidth() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.LargeImage.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.MediumImage.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.MediumImage.Height createItemSearchResponseItemsItemImageSetsImageSetMediumImageHeight() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.MediumImage.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.MediumImage.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.MediumImage.Width createItemSearchResponseItemsItemImageSetsImageSetMediumImageWidth() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.MediumImage.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.TinyImage.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.TinyImage.Height createItemSearchResponseItemsItemImageSetsImageSetTinyImageHeight() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.TinyImage.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.TinyImage.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.TinyImage.Width createItemSearchResponseItemsItemImageSetsImageSetTinyImageWidth() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.TinyImage.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.ThumbnailImage.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.ThumbnailImage.Height createItemSearchResponseItemsItemImageSetsImageSetThumbnailImageHeight() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.ThumbnailImage.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.ThumbnailImage.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.ThumbnailImage.Width createItemSearchResponseItemsItemImageSetsImageSetThumbnailImageWidth() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.ThumbnailImage.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.SmallImage.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.SmallImage.Height createItemSearchResponseItemsItemImageSetsImageSetSmallImageHeight() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.SmallImage.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.SmallImage.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.SmallImage.Width createItemSearchResponseItemsItemImageSetsImageSetSmallImageWidth() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.SmallImage.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.SwatchImage.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.SwatchImage.Height createItemSearchResponseItemsItemImageSetsImageSetSwatchImageHeight() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.SwatchImage.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ImageSets.ImageSet.SwatchImage.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.ImageSets.ImageSet.SwatchImage.Width createItemSearchResponseItemsItemImageSetsImageSetSwatchImageWidth() {
        return new ItemSearchResponse.Items.Item.ImageSets.ImageSet.SwatchImage.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.LargeImage.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.LargeImage.Height createItemSearchResponseItemsItemLargeImageHeight() {
        return new ItemSearchResponse.Items.Item.LargeImage.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.LargeImage.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.LargeImage.Width createItemSearchResponseItemsItemLargeImageWidth() {
        return new ItemSearchResponse.Items.Item.LargeImage.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.MediumImage.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.MediumImage.Height createItemSearchResponseItemsItemMediumImageHeight() {
        return new ItemSearchResponse.Items.Item.MediumImage.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.MediumImage.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.MediumImage.Width createItemSearchResponseItemsItemMediumImageWidth() {
        return new ItemSearchResponse.Items.Item.MediumImage.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.SmallImage.Height }
     * 
     */
    public ItemSearchResponse.Items.Item.SmallImage.Height createItemSearchResponseItemsItemSmallImageHeight() {
        return new ItemSearchResponse.Items.Item.SmallImage.Height();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.SmallImage.Width }
     * 
     */
    public ItemSearchResponse.Items.Item.SmallImage.Width createItemSearchResponseItemsItemSmallImageWidth() {
        return new ItemSearchResponse.Items.Item.SmallImage.Width();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Item.ItemLinks.ItemLink }
     * 
     */
    public ItemSearchResponse.Items.Item.ItemLinks.ItemLink createItemSearchResponseItemsItemItemLinksItemLink() {
        return new ItemSearchResponse.Items.Item.ItemLinks.ItemLink();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.Items.Request.ItemSearchRequest }
     * 
     */
    public ItemSearchResponse.Items.Request.ItemSearchRequest createItemSearchResponseItemsRequestItemSearchRequest() {
        return new ItemSearchResponse.Items.Request.ItemSearchRequest();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.OperationRequest.Arguments.Argument }
     * 
     */
    public ItemSearchResponse.OperationRequest.Arguments.Argument createItemSearchResponseOperationRequestArgumentsArgument() {
        return new ItemSearchResponse.OperationRequest.Arguments.Argument();
    }

    /**
     * Create an instance of {@link ItemSearchResponse.OperationRequest.HTTPHeaders.Header }
     * 
     */
    public ItemSearchResponse.OperationRequest.HTTPHeaders.Header createItemSearchResponseOperationRequestHTTPHeadersHeader() {
        return new ItemSearchResponse.OperationRequest.HTTPHeaders.Header();
    }

}
